name: Docker Build Workflow
on:
  push:
    branches: [main, dev]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com
  DOCKER_REPO_NAME: ${{ secrets.DOCKER_USER }}/test-go-app
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go vet ./

      - name: Output tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Docker Image
        working-directory: ./
        run: docker build . --file Dockerfile --tag my-app-test:${{ env.RELEASE_VERSION }}

      - name: Login to Docker Hub
        run: docker login -u ${{ env.DOCKER_USER }} -p ${{ env.DOCKER_PASSWORD }}

      - name: Output docker images
        run: docker images

      - name: Push Image to Docker Hub
        working-directory: ./
        run: docker push ${{ env.DOCKER_REPO_NAME }}:${{ env.RELEASE_VERSION }}
