name: Docker Build Workflow
on:
  push:
    branches: [main, dev]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Output tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: Build Docker Image
        working-directory: ./
        run: docker build . --file Dockerfile --tag my-app-test:${{ steps.vars.outputs.tag }}
