name: Docker Build Workflow
on:
  push:
    branches: [main, dev]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com
  DOCKER_REPO_NAME: ${{ secrets.DOCKER_USER }}/test-go-app
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: go vet ./

      - name: Output tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Build Docker Image
        working-directory: ./
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_REPO_NAME }}:${{ env.RELEASE_VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Push Image to Docker Hub
        working-directory: ./
        run: docker push ${{ env.DOCKER_REPO_NAME }}:${{ env.RELEASE_VERSION }}

      - name: Send notification of failed build
        if: failure()
        run: echo 'Notification will be send!'
