name: Docker Build Workflow
on:
  push:
    branches: [main, dev]
    tags:
      - '[\d]+[.][\d]+[.][\d]+'
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        working-directory: ./
        run: docker build . --file Dockerfile --tag my-app-test:latest
